/* Generated by Yosys 0.13 (git sha1 UNKNOWN, clang 13.0.0 -fPIC -Os) */

module test(x, s, clk, r);
  wire _0_;
  input clk;
  output r;
  input s;
  input x;
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(r),
    .A1(x),
    .S(s),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(r)
  );
endmodule
