/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test3(x, y, s1, s2, clk, r, r2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input clk;
  output [3:0] r;
  output r2;
  input s1;
  input s2;
  input [3:0] x;
  input [3:0] y;
  sky130_fd_sc_hd__nand2_1 _20_ (
    .A(y[0]),
    .B(x[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(y[0]),
    .B(x[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(r[0]),
    .B(s1),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(s1),
    .A2(_06_),
    .B1(_07_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(y[1]),
    .B(x[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(y[1]),
    .B(x[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(_05_),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(s1),
    .B(r[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a21oi_1 _28_ (
    .A1(s1),
    .A2(_10_),
    .B1(_11_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21ai_0 _29_ (
    .A1(_05_),
    .A2(_09_),
    .B1(_08_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(y[2]),
    .B(x[2]),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _32_ (
    .A(s1),
    .B(r[2]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _33_ (
    .A1(s1),
    .A2(_14_),
    .B1(_15_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(s1),
    .B(r[3]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(y[2]),
    .B(x[2]),
    .C(_12_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(y[3]),
    .B(x[3]),
    .X(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_17_),
    .B(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(s1),
    .A2(_19_),
    .B1(_16_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _39_ (
    .A0(r2),
    .A1(x[0]),
    .S(s2),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_00_),
    .Q(r2)
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_01_),
    .Q(r[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_02_),
    .Q(r[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_03_),
    .Q(r[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_04_),
    .Q(r[3])
  );
endmodule
